    ###> apache-php ###
    app:
        build:
            context: ./
            args:
                APACHE_IMAGE: '${APACHE_IMAGE}'
            dockerfile: ${APP_DOCKERFILE}
        hostname: localhost
        environment:
            TZ: Europe/Paris
            APP_ENV: dev
            CORS_ALLOW_ORIGIN: '*'
            DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@${APP_NAME}_db:3306/${APP_NAME}?serverVersion=${DB_IMAGE}-${DB_VERSION}'
            MAILER_DSN: ${MAILER_DSN_DEV}
        container_name: ${APP_NAME}_app
        volumes:
            - ./infra/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
            - ./infra/php/php.ini:/usr/local/etc/php/conf.d/app.ini
            - ./infra/scripts/entrypoint_dev.sh:/var/www/entrypoint.sh
            - ./app/:/var/www/html:rw
        ports:
            - "80:80"
    ### apache-php ###
