    ###> apache-php ###
    app:
        image: ${APP_NAME}_app
        hostname: localhost
        environment:
            TZ: Europe/Paris
            APP_ENV: dev
        volumes:
            - ./.docker/apache/vhost.conf:/etc/apache2/sites-available/000-default.conf
            - ./.docker/php/php.ini:/usr/local/etc/php/conf.d/app.ini
            - ./.docker/scripts/entrypoint_dev.sh:/var/www/entrypoint.sh
            - ./app/:/var/www/html:rw
        ports:
            - "80:80"
    ### apache-php ###
