    ###> apache-php ###
    app:
        build:
            context: ./
            args:
                APACHE_IMAGE: '${APACHE_IMAGE}'
                NODE_IMAGE: '${NODE_IMAGE}'
            dockerfile: ${APP_DOCKERFILE}
        image: ${APP_NAME}_app:${APP_TAG}
        container_name: ${APP_NAME}_app
        hostname: ${APP_NAME}.${PROD_HOST_NAME}
        environment:
            TZ: Europe/Paris
            APP_ENV: prod
            APP_FOLDER: ${APP_FOLDER}
            CORS_ALLOW_ORIGIN: '*'
            DATABASE_URL: 'mysql://${DB_USER}:${DB_PASSWORD}@${APP_NAME}_db:3306/${APP_NAME}?serverVersion=${DB_IMAGE}-${DB_VERSION}'
            MAILER_DSN: ${MAILER_DSN_PROD}
        networks:
            - localNetwork
            - webgateway
        labels:
            - traefik.enable=true
            - traefik.http.routers.${APP_NAME}.rule=Host(`${APP_NAME}.${PROD_HOST_NAME}`)
            - traefik.http.routers.${APP_NAME}.entrypoints=webgateway
            - traefik.docker.network=webgateway
            - traefik.http.services.${APP_NAME}.loadbalancer.server.port=80
    ### apache-php ###
