    ###> maildev ###
    maildev:
        image: djfarrelly/maildev
        container_name: maildev
        command: 'bin/maildev --web 80 --smtp 25 --hide-extensions STARTTLS'
        ports:
            - '25:25'
            - '1080:80'
        networks:
            - localNetwork
    ### maildev ###
