    ###> redis ###
    cache:
        image: ${REDIS_IMAGE}
        restart: always
        command: redis-server --save 20 1 --loglevel warning --requirepass ${REDIS_PASSWORD}
        volumes: 
            - '/data/${APP_NAME}/cache:/data'
        networks:
            - localNetwork
    ### redis ###
