    ###> elasticsearch ###
    elasticsearch:
        volumes:
            - 'esdata:/usr/share/elasticsearch/data'
        ports:
            - '9200:9200'
    kibana:
        ports:
            - '5601:5601'
    ### elasticsearch ###
