    ###> rabbitmq ###
    rabbitmq:
        image: ${RABBITMQ_IMAGE}
        container_name: rabbitmq
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_PASSWORD}
        networks:
            - localNetwork
            - webgateway
        labels:
            - traefik.enable=true
            - traefik.http.routers.${APP_NAME}.rule=Host(`rabbitmq-${APP_NAME}.${HOST_NAME}`)
            - traefik.http.routers.${APP_NAME}.entrypoints=webgateway
            - traefik.docker.network=webgateway
            - traefik.http.services.${APP_NAME}.loadbalancer.server.port=5672
    ### rabbitmq ###
